#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    Sep 15, 2020 02:27:31 PM +07  platform: Windows NT
import os
try:
    import tkinter
except:
    os.system('apt-get install -y python3-tk')
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import modules.JN_INSTALLER_support as JN_INSTALLER_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    JN_INSTALLER_support.set_Tk_var()
    top = Toplevel1 (root)
    JN_INSTALLER_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    JN_INSTALLER_support.set_Tk_var()
    top = Toplevel1 (w)
    JN_INSTALLER_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("588x450+675+183")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("JETSON NANO INSTALLER")
        top.configure(borderwidth="5")
        top.configure(background="#00ff80")
        top.configure(highlightbackground="#ffff80")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=0.022, relheight=0.978, relwidth=1.0)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#008040")
        self.Frame1.configure(highlightbackground="#004000")
        self.Frame1.configure(highlightcolor="#008000")

        self.Checkbutton1 = tk.Checkbutton(self.Frame1)
        self.Checkbutton1.place(relx=0.051, rely=0.477, relheight=0.057
                , relwidth=1.133)
        self.Checkbutton1.configure(activebackground="#004000")
        self.Checkbutton1.configure(activeforeground="white")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(anchor='nw')
        self.Checkbutton1.configure(background="#000000")
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(foreground="#ffffff")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(selectcolor="#000000")
        self.Checkbutton1.configure(text='''OPENCV 4.5.0 WITH CUDA''')
        self.Checkbutton1.configure(variable=JN_INSTALLER_support.Var3)

        self.Canvas1 = tk.Canvas(self.Frame1)
        self.Canvas1.place(relx=0.051, rely=0.045, relheight=0.191
                , relwidth=0.912)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")

        self.Label1 = tk.Label(self.Canvas1)
        self.Label1.place(relx=0.019, rely=0.119, height=62, width=507)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#000000")
        self.Label1.configure(borderwidth="12")
        self.Label1.configure(compound='center')
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {OCR A Extended} -size 20 -weight bold -slant italic -underline 1 -overstrike 0")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''CHOOSE LIBRARIES TO INSTALL''')

        self.Checkbutton1_1 = tk.Checkbutton(self.Frame1)
        self.Checkbutton1_1.place(relx=0.051, rely=0.409, relheight=0.057
                , relwidth=1.133)
        self.Checkbutton1_1.configure(activebackground="#004000")
        self.Checkbutton1_1.configure(activeforeground="white")
        self.Checkbutton1_1.configure(activeforeground="#000000")
        self.Checkbutton1_1.configure(anchor='nw')
        self.Checkbutton1_1.configure(background="#000000")
        self.Checkbutton1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_1.configure(foreground="#ffffff")
        self.Checkbutton1_1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_1.configure(highlightcolor="black")
        self.Checkbutton1_1.configure(justify='left')
        self.Checkbutton1_1.configure(selectcolor="#000000")
        self.Checkbutton1_1.configure(text='''DLIB + FACE_RECOGNITION''')
        self.Checkbutton1_1.configure(variable=JN_INSTALLER_support.Var2)

        self.Checkbutton1_2 = tk.Checkbutton(self.Frame1)
        self.Checkbutton1_2.place(relx=0.051, rely=0.75, relheight=0.057
                , relwidth=1.133)
        self.Checkbutton1_2.configure(activebackground="#004000")
        self.Checkbutton1_2.configure(activeforeground="white")
        self.Checkbutton1_2.configure(activeforeground="#000000")
        self.Checkbutton1_2.configure(anchor='nw')
        self.Checkbutton1_2.configure(background="#000000")
        self.Checkbutton1_2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_2.configure(foreground="#ffffff")
        self.Checkbutton1_2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_2.configure(highlightcolor="black")
        self.Checkbutton1_2.configure(justify='left')
        self.Checkbutton1_2.configure(selectcolor="#000000")
        self.Checkbutton1_2.configure(text='''WXPYTHON''')
        self.Checkbutton1_2.configure(variable=JN_INSTALLER_support.Var7)

        self.Checkbutton1_3 = tk.Checkbutton(self.Frame1)
        self.Checkbutton1_3.place(relx=0.051, rely=0.273, relheight=0.057
                , relwidth=1.133)
        self.Checkbutton1_3.configure(activebackground="#000000")
        self.Checkbutton1_3.configure(activeforeground="white")
        self.Checkbutton1_3.configure(activeforeground="#000000")
        self.Checkbutton1_3.configure(anchor='nw')
        self.Checkbutton1_3.configure(background="#000000")
        self.Checkbutton1_3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_3.configure(foreground="#ffffff")
        self.Checkbutton1_3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_3.configure(highlightcolor="black")
        self.Checkbutton1_3.configure(justify='left')
        self.Checkbutton1_3.configure(selectcolor="#000000")
        self.Checkbutton1_3.configure(text='''INSTALL SYSTEM-LEVEL LIB + CHECK UPDATE + PIP3''')
        self.Checkbutton1_3.configure(variable=JN_INSTALLER_support.Var0)

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.578, rely=0.841, height=54, width=257)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#003700")
        self.Button1.configure(command=JN_INSTALLER_support.install_now_but)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {VNI-DOS Sample Font } -size 14 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''INSTALL NOW''')
        self.Button1.configure(textvariable=JN_INSTALLER_support.install_but)

        self.Checkbutton1_4 = tk.Checkbutton(self.Frame1)
        self.Checkbutton1_4.place(relx=0.051, rely=0.682, relheight=0.057
                , relwidth=1.133)
        self.Checkbutton1_4.configure(activebackground="#004000")
        self.Checkbutton1_4.configure(activeforeground="white")
        self.Checkbutton1_4.configure(activeforeground="#000000")
        self.Checkbutton1_4.configure(anchor='nw')
        self.Checkbutton1_4.configure(background="#000000")
        self.Checkbutton1_4.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_4.configure(foreground="#ffffff")
        self.Checkbutton1_4.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_4.configure(highlightcolor="black")
        self.Checkbutton1_4.configure(justify='left')
        self.Checkbutton1_4.configure(selectcolor="#000000")
        self.Checkbutton1_4.configure(text='''UPDATE CMAKE''')
        self.Checkbutton1_4.configure(variable=JN_INSTALLER_support.Var6)

        self.Checkbutton1_5 = tk.Checkbutton(self.Frame1)
        self.Checkbutton1_5.place(relx=0.051, rely=0.341, relheight=0.057
                , relwidth=1.133)
        self.Checkbutton1_5.configure(activebackground="#000000")
        self.Checkbutton1_5.configure(activeforeground="white")
        self.Checkbutton1_5.configure(activeforeground="#000000")
        self.Checkbutton1_5.configure(anchor='nw')
        self.Checkbutton1_5.configure(background="#000000")
        self.Checkbutton1_5.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_5.configure(foreground="#ffffff")
        self.Checkbutton1_5.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_5.configure(highlightcolor="black")
        self.Checkbutton1_5.configure(justify='left')
        self.Checkbutton1_5.configure(selectcolor="#000000")
        self.Checkbutton1_5.configure(text='''CREATE ZRAM (6GB) + MAXIMUM PROCESS''')
        self.Checkbutton1_5.configure(variable=JN_INSTALLER_support.Var1)

        self.Checkbutton1_1 = tk.Checkbutton(self.Frame1)
        self.Checkbutton1_1.place(relx=0.051, rely=0.545, relheight=0.057
                , relwidth=1.133)
        self.Checkbutton1_1.configure(activebackground="#004000")
        self.Checkbutton1_1.configure(activeforeground="white")
        self.Checkbutton1_1.configure(activeforeground="#000000")
        self.Checkbutton1_1.configure(anchor='nw')
        self.Checkbutton1_1.configure(background="#000000")
        self.Checkbutton1_1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_1.configure(foreground="#ffffff")
        self.Checkbutton1_1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_1.configure(highlightcolor="black")
        self.Checkbutton1_1.configure(justify='left')
        self.Checkbutton1_1.configure(selectcolor="#000000")
        self.Checkbutton1_1.configure(text='''JTOP (GPU DISPLAY)''')
        self.Checkbutton1_1.configure(variable=JN_INSTALLER_support.Var4)

        self.Checkbutton1_2 = tk.Checkbutton(self.Frame1)
        self.Checkbutton1_2.place(relx=0.051, rely=0.614, relheight=0.057
                , relwidth=1.133)
        self.Checkbutton1_2.configure(activebackground="#004000")
        self.Checkbutton1_2.configure(activeforeground="white")
        self.Checkbutton1_2.configure(activeforeground="#000000")
        self.Checkbutton1_2.configure(anchor='nw')
        self.Checkbutton1_2.configure(background="#000000")
        self.Checkbutton1_2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1_2.configure(foreground="#ffffff")
        self.Checkbutton1_2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1_2.configure(highlightcolor="black")
        self.Checkbutton1_2.configure(justify='left')
        self.Checkbutton1_2.configure(selectcolor="#000000")
        self.Checkbutton1_2.configure(text='''VISUAL STUDIO CODE''')
        self.Checkbutton1_2.configure(variable=JN_INSTALLER_support.Var5)

if __name__ == '__main__':
    vp_start_gui()





